PY_EXPERIMENTER:
  n_jobs: 1

  Database:
    provider: mysql
    database: AgentSmac
    table:
      name: AgentSmacRuns_tabular
      keyfields:
        dataset_origin:
          type: VARCHAR(255)
          values: ['openml']
        dataset_name:
          type: VARCHAR(255)
          values: ['openml']
        dataset_type:
          type: VARCHAR(255)
          values: ['tabular']
        task_type:
          type: VARCHAR(255)
          values: ['classification']
        llm_model:
          type: VARCHAR(255)
          values: ['llama-3.3-70b-instruct']
        dataset_openml_id:
          type: int
          values: [1489]
          # values: [1489, 23517, 28, 715, 752, 772, 807, 354]  # Default to credit-g dataset ID
        time_budget:
          type: int
          values: [21600]
        metric:
          type: VARCHAR(255)
          values: ['accuracy']
        n_folds:
          type: int
          values: [10]
        fold:
          type: int
          values:
            start: 1
            stop: 10 # Only one seed to keep experiment size small
            step: 1
        n_gpus:
          type: int
          values: [1]
        n_cpus:
          type: int
          values: [16]
        n_gb_ram:
          type: int
          values: [16]
      result_timestamps: True
      resultfields:
        test_accuracy: FLOAT
        test_balanced_accuracy: FLOAT
        test_mcc: FLOAT
        test_roc_auc: FLOAT
        test_f1: FLOAT
        test_precision: FLOAT
        test_recall: FLOAT
        log_dir: VARCHAR(255)
  Custom:
    datapath: sample_data