PY_EXPERIMENTER:
  n_jobs: 1

  Database:
    provider: mysql
    database: AgentSmac
    table:
      name: AgentSmacRuns_tabular_regression
      keyfields:
        dataset_origin:
          type: VARCHAR(255)
          values: ['openml']
        dataset_name:
          type: VARCHAR(255)
          values: ['openmlregression']
        dataset_type:
          type: VARCHAR(255)
          values: ['tabular']
        task_type:
          type: VARCHAR(255)
          values: ['regression']
        llm_model:
          type: VARCHAR(255)
          values: ['llama-3.3-70b-instruct']
        dataset_openml_id:
          type: int
          values: [44973, 44977]  # California Housing, Diabetes, Boston Housing, Energy Efficiency, Concrete Strength
        time_budget:
          type: int
          values: [3600]  # 1h, 2h, 4h time budgets
        metric:
          type: VARCHAR(255)
          values: ['mse']  # Regression metrics
        n_folds:
          type: int
          values: [10]
        fold:
          type: int
          values:
            start: 1
            stop: 10  # Reduced to 5 folds for faster experimentation
            step: 1
        n_gpus:
          type: int
          values: [1]
        n_cpus:
          type: int
          values: [16]
        n_gb_ram:
          type: int
          values: [16]
      result_timestamps: True
      resultfields:
        test_mse: FLOAT
        test_mae: FLOAT
        test_r2: FLOAT
        log_dir: VARCHAR(255)
  Custom:
    datapath: sample_data 